CREATE VIEW [dbo].[VW_DOC_INFO]
--WITH SCHEMABINDING
AS
     SELECT [DocId], 
            [DocPeriodId], 
            [DocDoctypeId], 
            [DocEnterdate], 
            [DocEnterno], 
            [DocEnternop1], 
            [DocEnternop2], 
            [DocRegisterId], 
            [DocEnternoControl], 
            [DocDocno], 
            [DocDocdate], 
            [DocOrganizationId], 
            [DocDuplicateDocId], 
            [DocDuplicateId], 
            [DocFormId], 
            [DocReceivedFormId], 
            [DocPageCount], 
            [DocCopiesCount], 
            [DocAttachmentCount], 
            [DocAppliertypeId], 
            [DocUndercontrolStatusId], 
            [DocUndercontrolDayCount], 
            [DocControlStatusId], 
            [DocDocumentstatusId], 
            [DocDescription], 
            [DocTopDepartmentId], 
            [DocPlannedDate], 
            [DocReportedDate], 
            [DocExecutedDate], 
            [DocProlongDate], 
            [DocSendDate], 
            [DocControlNotes], 
            [DocApplytypeId], 
            [DocTopicId], 
            [DocTopicType], 
            [DocExecutionStatusId], 
            [DocSendedDocumentId], 
            [DocSendTypeId], 
            [DocClosed], 
            [DocDeleted], 
            [DocInsertedById], 
            [DocInsertedByDate], 
            [DocUpdatedById], 
            [DocUpdatedByDate], 
            [DocIsAppealBoard], 
            [DocDocumentOldStatusId], 
            [DocResultId]
     FROM dbo.DOCS
     WHERE DocDeleted IN(0, 2);

