//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzDoc.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzDoc.App_LocalResources.RLang", typeof(RLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müəllif.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müəllifi daxil edin.
        /// </summary>
        public static string AuthorEnter {
            get {
                return ResourceManager.GetString("AuthorEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş etdiyiniz istifadəçinin səlahiyyətləri əvəz olunub.
        /// </summary>
        public static string AuthorityLoginFail {
            get {
                return ResourceManager.GetString("AuthorityLoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müəllif.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müəllifin adı siyahıda tapılmadı.
        /// </summary>
        public static string AuthorNotFound {
            get {
                return ResourceManager.GetString("AuthorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əsas məlumatlar.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faylı seçin.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xanalar.
        /// </summary>
        public static string btSearchColumnsShowModal {
            get {
                return ResourceManager.GetString("btSearchColumnsShowModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ləğv et.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəni dəyiş.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəni unutmusan?.
        /// </summary>
        public static string ChangePasswordQuestion {
            get {
                return ResourceManager.GetString("ChangePasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi şifrəsini dəyişdirmək.
        /// </summary>
        public static string ChangePasswordText {
            get {
                return ResourceManager.GetString("ChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağla.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təsdiq et.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat silinsin?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni şifrə və yeni şifrənin təsdiqi uyğun deyil.
        /// </summary>
        public static string ConfirmPasswordCompare {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fayl silinsin?.
        /// </summary>
        public static string ConfirmText {
            get {
                return ResourceManager.GetString("ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nəzarət.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nüsxə.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göstəricilər paneli.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarix.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizanın silinməsi.
        /// </summary>
        public static string DeleteVizaTitle {
            get {
                return ResourceManager.GetString("DeleteVizaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şöbə.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dərkənar tarixi.
        /// </summary>
        public static string DirectionDate {
            get {
                return ResourceManager.GetString("DirectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İcraçını dəyiş.
        /// </summary>
        public static string DirectionExecutorChange {
            get {
                return ResourceManager.GetString("DirectionExecutorChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İcra haqqında məlumat.
        /// </summary>
        public static string DirectionInfo {
            get {
                return ResourceManager.GetString("DirectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İcraçını / İcra müddətini dəyiş.
        /// </summary>
        public static string DirectionInfoChange {
            get {
                return ResourceManager.GetString("DirectionInfoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İcra müddətini dəyiş.
        /// </summary>
        public static string DirectionPlannedDateChange {
            get {
                return ResourceManager.GetString("DirectionPlannedDateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sənəd məlumatları.
        /// </summary>
        public static string DocInfo {
            get {
                return ResourceManager.GetString("DocInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüklə.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyni vaxtda bir neçə brauzerdən girişə icazə yoxdur.
        /// </summary>
        public static string DuplicateLogin {
            get {
                return ResourceManager.GetString("DuplicateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redaktə et.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qoşma sənədlər.
        /// </summary>
        public static string EDocuments {
            get {
                return ResourceManager.GetString("EDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektron sənədlər.
        /// </summary>
        public static string EDocumentsView {
            get {
                return ResourceManager.GetString("EDocumentsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nəzarət müddəti.
        /// </summary>
        public static string ExecuteDate {
            get {
                return ResourceManager.GetString("ExecuteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əsas fayl kimi seçmək istədiyinizə əminsiniz?.
        /// </summary>
        public static string FileIsMainConfirm {
            get {
                return ResourceManager.GetString("FileIsMainConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sənəd tapılmadı.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sənədlər.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sənədə nömrə verilsin.
        /// </summary>
        public static string GenerateNumber {
            get {
                return ResourceManager.GetString("GenerateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kömək.
        /// </summary>
        public static string Helper {
            get {
                return ResourceManager.GetString("Helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əsas sənəd.
        /// </summary>
        public static string IsMainFile {
            get {
                return ResourceManager.GetString("IsMainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İcra tarixi.
        /// </summary>
        public static string LastExecuteDate {
            get {
                return ResourceManager.GetString("LastExecuteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sənəd növləri.
        /// </summary>
        public static string LeftPanelDocType {
            get {
                return ResourceManager.GetString("LeftPanelDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtarış.
        /// </summary>
        public static string LeftPanelSearch {
            get {
                return ResourceManager.GetString("LeftPanelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAXİL OLUN.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçinin sistemə girişə icazəsi yoxdur.
        /// </summary>
        public static string LoginActiveStatus {
            get {
                return ResourceManager.GetString("LoginActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi adı və ya şifrə yanlışdır!.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tətbiqə giriş paneli.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıxış.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əsas icraçı.
        /// </summary>
        public static string MainExecutor {
            get {
                return ResourceManager.GetString("MainExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəni dəyiş.
        /// </summary>
        public static string MenuChangePassword {
            get {
                return ResourceManager.GetString("MenuChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana səhifə.
        /// </summary>
        public static string MenuDocuments {
            get {
                return ResourceManager.GetString("MenuDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükləmələr.
        /// </summary>
        public static string MenuDownloads {
            get {
                return ResourceManager.GetString("MenuDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk səhifə.
        /// </summary>
        public static string MenuFirstPage {
            get {
                return ResourceManager.GetString("MenuFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat kitabçaları.
        /// </summary>
        public static string MenuHandbooks {
            get {
                return ResourceManager.GetString("MenuHandbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xidmət.
        /// </summary>
        public static string MenuService {
            get {
                return ResourceManager.GetString("MenuService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sazlamalar.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Köhnə şifrə yenidən istifadə edilə bilinməz.
        /// </summary>
        public static string MustNotUseOldPassword {
            get {
                return ResourceManager.GetString("MustNotUseOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni sənəd.
        /// </summary>
        public static string NewDoc {
            get {
                return ResourceManager.GetString("NewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni müraciət.
        /// </summary>
        public static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni dərkənar.
        /// </summary>
        public static string NewResolution {
            get {
                return ResourceManager.GetString("NewResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni versiya.
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni viza.
        /// </summary>
        public static string NewViza {
            get {
                return ResourceManager.GetString("NewViza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İrəli.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xeyr.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeydlər.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirişlər.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təşkilatın məlumatları daxil edilməyib.
        /// </summary>
        public static string OrganizationEmpty {
            get {
                return ResourceManager.GetString("OrganizationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təşkilat.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təşkilatın adını siyahıdan seçin.
        /// </summary>
        public static string OrganizationNameEnter {
            get {
                return ResourceManager.GetString("OrganizationNameEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təşkilatın adı siyahıda tapılmadı.
        /// </summary>
        public static string OrganizationNotFound {
            get {
                return ResourceManager.GetString("OrganizationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə dəyişdirildi.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni şifrənin təsdiqi.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni şifrəni təsdiqləyin.
        /// </summary>
        public static string PasswordConfirmRequired {
            get {
                return ResourceManager.GetString("PasswordConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçinin şifrəsi səhvdir.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə təhlükəsiz deyil.
        /// </summary>
        public static string PasswordIsNotSecure {
            get {
                return ResourceManager.GetString("PasswordIsNotSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrənin uzunluğu 3 və daha çox simvoldan ibarət olmalıdır .
        /// </summary>
        public static string PasswordLenght {
            get {
                return ResourceManager.GetString("PasswordLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni şifrə.
        /// </summary>
        public static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni şifrəni daxil edin.
        /// </summary>
        public static string PasswordNewRequired {
            get {
                return ResourceManager.GetString("PasswordNewRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrələr üst üstə düşmür.
        /// </summary>
        public static string PasswordNotConfirmed {
            get {
                return ResourceManager.GetString("PasswordNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi şifrəsini daxil edin.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəxsi kabinet.
        /// </summary>
        public static string PersonalCabinet {
            get {
                return ResourceManager.GetString("PersonalCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vəzifə.
        /// </summary>
        public static string PositionName {
            get {
                return ResourceManager.GetString("PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geriyə.
        /// </summary>
        public static string PrevStep {
            get {
                return ResourceManager.GetString("PrevStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sual-Cavab.
        /// </summary>
        public static string QuestionsTabCaption {
            get {
                return ResourceManager.GetString("QuestionsTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeydiyyat vərəqəsi.
        /// </summary>
        public static string RegistrationForm {
            get {
                return ResourceManager.GetString("RegistrationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlaqəli sənədlər daxil edilməyiblər.
        /// </summary>
        public static string RelatedDocumentEmty {
            get {
                return ResourceManager.GetString("RelatedDocumentEmty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yadda saxla.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dəyiş.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabatlar.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müraciətə cavab.
        /// </summary>
        public static string RequestAnswer {
            get {
                return ResourceManager.GetString("RequestAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu xana məcburidir.
        /// </summary>
        public static string RequiredCell {
            get {
                return ResourceManager.GetString("RequiredCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezerv.
        /// </summary>
        public static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıfırlama kodu.
        /// </summary>
        public static string ResetCode {
            get {
                return ResourceManager.GetString("ResetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəni dəyişməyə icazəniz yoxdu.
        /// </summary>
        public static string ResetPasswordAdmin {
            get {
                return ResourceManager.GetString("ResetPasswordAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yadda saxla.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi profaylı verilməyib!.
        /// </summary>
        public static string SchemaFailed {
            get {
                return ResourceManager.GetString("SchemaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fayl server hal-hazırda işlək deyil. Zəhmət olmasa biraz sonra yenidən yoxlayın..
        /// </summary>
        public static string SftpWarning {
            get {
                return ResourceManager.GetString("SftpWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qısa məzmun.
        /// </summary>
        public static string ShortContent {
            get {
                return ResourceManager.GetString("ShortContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şablonlar.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nəzarətlə daxil olub.
        /// </summary>
        public static string UnderControl {
            get {
                return ResourceManager.GetString("UnderControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nəzarətlə.
        /// </summary>
        public static string UnderControlDays {
            get {
                return ResourceManager.GetString("UnderControlDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüklə.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi adı.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi adını daxil edin.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi profaylını seçin.
        /// </summary>
        public static string UserProfileRequired {
            get {
                return ResourceManager.GetString("UserProfileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xəbərdarlıq.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bəli.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
