CREATE TABLE [dbo].[DC_DEPARTMENTTYPE](
	[TypeId] int NOT NULL,
	[TypeName] nvarchar(250) NOT NULL,
	[TypeStatus] bit NOT NULL CONSTRAINT [DF__DC_DEPART__TypeS__3E52440B]  DEFAULT ((1)),
    CONSTRAINT [PK_DC_DEPARTMENTTYPE] PRIMARY KEY ([TypeId])
 )
