CREATE TABLE [dbo].[DC_ORGANIZATION](
	[OrganizationId] int identity NOT NULL,
	[OrganizationName] nvarchar(250) NOT NULL,
	[OrganizationShortname] nvarchar(250) NOT NULL,
	[OrganizationName2] nvarchar(250) NULL,
	[OrganizationName3] nvarchar(250) NULL,
	[OrganizationTopId] int NULL,
	[OrganizationTypeId] int NULL,
	[OrganizationRegionId] int NULL,
	[OrganizationZip] varchar(10) NULL,
	[OrganizationAddress] nvarchar(200) NULL,
	[OrganizationPhone] nvarchar(100) NULL,
	[OrganizationFax] nvarchar(100) NULL,
	[OrganizationChiefname] nvarchar(100) NULL,
	[OrganizationWebsite] nvarchar(100) NULL,
	[OrganizationEmail] varchar(100) NULL,
	[OrganizationCourtCode] char(3) NULL,
	[OrganizationIndex] nvarchar(25) NULL,
	[OrganizationStatus] bit NOT NULL CONSTRAINT [DF__DC_ORGANI__Organ__2E1BDC42]  DEFAULT ((1)),
	[OrganizationIndex2] nvarchar(25) NULL,
	[OrganizationIndex3] nvarchar(25) NULL,
    CONSTRAINT [PK_DC_ORGANIZATION] PRIMARY KEY ([OrganizationId]),
	CONSTRAINT [FK_DC_ORGANIZATION_DC_ORGANIZATIONTYPE] FOREIGN KEY([OrganizationTypeId]) REFERENCES [dbo].[DC_ORGANIZATIONTYPE] ([TypeId]),
	CONSTRAINT [FK_DC_ORGANIZATION_DC_REGION] FOREIGN KEY([OrganizationRegionId]) REFERENCES [dbo].[DC_REGION] ([RegionId])
 )
