CREATE TABLE [dbo].[DC_PERSONNEL](
	[PersonnelId] int identity NOT NULL,
	[PersonnelName] nvarchar(50) NOT NULL,
	[PersonnelSurname] nvarchar(50) NOT NULL,
	[PersonnelLastname] nvarchar(50) NULL,
	[PersonnelBirthdate] [date] NULL,
	[PersonnelSexId] int NOT NULL,
	[PersonnelFIN] nvarchar(10) NULL,
	[PersonnelRankId] int NULL,
	[PersonnelRegionId] int NULL,
	[PersonnelAddress] nvarchar(200) NULL,
	[PersonnelPhone] nvarchar(50) NULL,
	[PersonnelEmail] nvarchar(250) NULL,
	[PersonnelMobile] nvarchar(50) NULL,
	[PersonnelTabelcode] nvarchar(50) NULL,
	[PersonnelAsanPhoneId] varchar(100) NULL,
	[PersonnelAsanUserId] varchar(100) NULL,
	[PersonnelStatus] bit NULL CONSTRAINT [DF_DC_PERSONNEL_PersonnelStatus]  DEFAULT 1,
	[PersonnelInternalPhone] nvarchar(50) NULL,
	[AsanKey] nvarchar(30) NULL,
	[PersonnelNameEn] nvarchar(50) NULL,
	[PersonnelNameRu] nvarchar(50) NULL,
	[PersonnelSurnameEn] nvarchar(50) NULL,
	[PersonnelSurnameRu] nvarchar(50) NULL,
 CONSTRAINT [PK_DC_PERSONNEL] PRIMARY KEY ([PersonnelId]),
 CONSTRAINT [FK_DC_PERSONNEL_DC_RANK] FOREIGN KEY([PersonnelRankId]) REFERENCES [dbo].[DC_RANK] ([RankId]),
 CONSTRAINT [FK_DC_PERSONNEL_DC_REGION] FOREIGN KEY([PersonnelRegionId]) REFERENCES [dbo].[DC_REGION] ([RegionId]),
 CONSTRAINT [FK_DC_PERSONNEL_DC_SEX] FOREIGN KEY([PersonnelSexId]) REFERENCES [dbo].[DC_SEX] ([SexId])
 )
