CREATE TABLE [dbo].[DC_ROLE_OPERATION](
	[RoleOperationId] int identity NOT NULL,
	[RoleId] int NOT NULL,
	[OperationId] int NOT NULL,
	[RightId] int NULL,
	[RightTypeId] int NULL,
    CONSTRAINT [PK_DC_ROLE_OPERATION] PRIMARY KEY ([RoleOperationId]),
    CONSTRAINT [FK_DC_ROLE_OPERATION_DC_OPERATION] FOREIGN KEY([OperationId]) REFERENCES [dbo].[DC_OPERATION] ([OperationId]),
    CONSTRAINT [FK_DC_ROLE_OPERATION_DC_RIGHT] FOREIGN KEY([RightId]) REFERENCES [dbo].[DC_RIGHT] ([RightId]),
    CONSTRAINT [FK_DC_ROLE_OPERATION_DC_RIGHT_TYPE] FOREIGN KEY([RightTypeId]) REFERENCES [dbo].[DC_RIGHT_TYPE] ([RightTypeId]),
    CONSTRAINT [FK_DC_ROLE_OPERATION_DC_ROLE] FOREIGN KEY([RoleId]) REFERENCES [dbo].[DC_ROLE] ([RoleId])
)
