CREATE TABLE [dbo].[DC_WORKPLACE_ROLE](
	[Id] int identity NOT NULL,
	[WorkplaceId] int NOT NULL,
	[RoleId] int NOT NULL,
	[Status] bit NULL CONSTRAINT [DF_DC_WORKPLACE_ROLE_Status]  DEFAULT 1,
	[InsertDate] [datetime] NULL CONSTRAINT [DF_YourTable]  DEFAULT (dbo.SYSDATETIME()),
    CONSTRAINT [PK_DC_USERPROFILE_ROLE] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_DC_USERPROFILE_ROLE_DC_ROLE1] FOREIGN KEY([RoleId]) REFERENCES [dbo].[DC_ROLE] ([RoleId]),
    CONSTRAINT [FK_DC_USERPROFILE_ROLE_DC_WORKPLACE] FOREIGN KEY([WorkplaceId]) REFERENCES [dbo].[DC_WORKPLACE] ([WorkplaceId])
)
