CREATE TABLE [dbo].[DM_ORG_SCHEMA](
	[OrganizationId] int NOT NULL,
	[SchemaId] int NULL,
   CONSTRAINT [PK_DM_ORG_SCHEMA] PRIMARY KEY ([OrganizationId]),
   CONSTRAINT [FK_DM_ORG_SCHEMA_DC_ORGANIZATION] FOREIGN KEY([OrganizationId]) REFERENCES [dbo].[DC_ORGANIZATION] ([OrganizationId]),
   CONSTRAINT [FK_DM_ORG_SCHEMA_DM_SCHEMA] FOREIGN KEY([SchemaId]) REFERENCES [dbo].[DM_SCHEMA] ([SchemaId])
 )
