CREATE TABLE [dbo].[DM_ORGGROUP_SCHEMA](
	[OrgGroupId] int identity NOT NULL,
	[SchemaId] int NOT NULL,
	[OrganizationId] int NOT NULL,
	[GroupTypeId] int NOT NULL,
    CONSTRAINT [PK_DM_ORGGROUP_SCHEMA] PRIMARY KEY ([OrgGroupId]),
    CONSTRAINT [FK_DM_ORGGROUP_SCHEMA_DC_ORGANIZATION] FOREIGN KEY([OrganizationId]) REFERENCES [dbo].[DC_ORGANIZATION] ([OrganizationId]),
    CONSTRAINT [FK_DM_ORGGROUP_SCHEMA_DM_ORGGROUP_TYPE] FOREIGN KEY([GroupTypeId]) REFERENCES [dbo].[DM_ORGGROUP_TYPE] ([GroupTypeId]),
    CONSTRAINT [FK_DM_ORGGROUP_SCHEMA_DM_SCHEMA] FOREIGN KEY([SchemaId]) REFERENCES [dbo].[DM_SCHEMA] ([SchemaId])
 )
