CREATE TABLE [dbo].[DOC_EXCHANGE](
	[Id] int identity NOT NULL,
	[OrgId] int NOT NULL,
	[WorkplaceId] int NOT NULL,
	[DocTypeId] int NOT NULL,
	[ChangeDocTypeId] int NOT NULL,
    CONSTRAINT [PK_DOC_EXCHANGE] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_DOC_EXCHANGE_DC_ORGANIZATION] FOREIGN KEY([OrgId]) REFERENCES [dbo].[DC_ORGANIZATION] ([OrganizationId]),
    CONSTRAINT [FK_DOC_EXCHANGE_DC_WORKPLACE] FOREIGN KEY([WorkplaceId]) REFERENCES [dbo].[DC_WORKPLACE] ([WorkplaceId]),
    CONSTRAINT [FK_DOC_EXCHANGE_DOC_TYPE] FOREIGN KEY([DocTypeId]) REFERENCES [dbo].[DOC_TYPE] ([DocTypeId])
)