CREATE TABLE [dbo].[DOCS_MODERATOR](
	[Id] int identity NOT NULL,
	[DocId] int NOT NULL,
	[ChangeData] nvarchar(max) NOT NULL,
	[UserId] int NOT NULL,
	[UpdateDate] [datetime] NOT NULL,
    CONSTRAINT [PK_DOCS_MODERATOR] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_DOCS_MODERATOR_DC_USER] FOREIGN KEY([UserId]) REFERENCES [dbo].[DC_USER] ([UserId]),
    CONSTRAINT [FK_DOCS_MODERATOR_DOCS_MODERATOR] FOREIGN KEY([Id]) REFERENCES [dbo].[DOCS_MODERATOR] ([Id])
)
