CREATE TABLE [dbo].[DOCS_DIRECTIONS](
	[DirectionId] int identity NOT NULL,
	[DirectionDocId] int NOT NULL,
	[DirectionDate] [datetime] NOT NULL,
	[DirectionWorkplaceId] int NULL,
	[DirectionPersonFullName] nvarchar(500) NULL,
	[DirectionTemplateId] int NULL,
	[DirectionTypeId] int NOT NULL,
	[DirectionControlStatus] bit NULL CONSTRAINT [DF__DOCS_DIRE__Direc__31D75E8D]  DEFAULT 0,
	[DirectionPlanneddate] [date] NULL,
	[DirectionPlannedDay] [tinyint] NULL,
	[DirectionExecutionStatusId] int NULL,
	[DirectionVizaId] int NULL,
	[DirectionConfirmed] [tinyint] NULL CONSTRAINT [DF__DOCS_DIRE__Direc__32CB82C6]  DEFAULT 1,
	[DirectionSendStatus] bit NULL,
	[DirectionCreatorWorkplaceId] int NULL,
	[DirectionInsertedDate] [datetime] NULL,
	[DirectionPersonId] int NULL,
	[DirectionUnixTime] [bigint] NULL,
	[DirectionNote] nvarchar(500) NULL,
	[DirectionConfirmPersonId] int NULL,
	[DirectionConfirmWorkplaceId] int NULL,
    CONSTRAINT [PK_DOCS_DIRECTIONS] PRIMARY KEY ([DirectionId]),
    CONSTRAINT [FK_DOCS_DIRECTIONS_DC_WORKPLACE] FOREIGN KEY([DirectionWorkplaceId]) REFERENCES [dbo].[DC_WORKPLACE] ([WorkplaceId]),
	CONSTRAINT [FK_DOCS_DIRECTIONS_DOC_DIRECTION_TEMPLATE] FOREIGN KEY([DirectionTemplateId]) REFERENCES [dbo].[DOC_DIRECTION_TEMPLATE] ([DirTemplateId]),
	CONSTRAINT [FK_DOCS_DIRECTIONS_DOC_EXECUTIONSTATUS] FOREIGN KEY([DirectionExecutionStatusId]) REFERENCES [dbo].[DOC_EXECUTIONSTATUS] ([ExecutionstatusId])
 )
