CREATE TABLE [dbo].[DOCS_ADDITION](
	[DocsAdditionId] int identity NOT NULL,
	[DocumentId] int NOT NULL,
	[Field1] [float] NULL,
	[Field2] [float] NULL,
	[Field3] [float] NULL,
	[Field4] [float] NULL,
	[Field5] [float] NULL,
	[Field6] nvarchar(200) NULL,
	[Field7] nvarchar(200) NULL,
	[Field8] nvarchar(200) NULL,
	[Field9] nvarchar(200) NULL,
	[Field10] nvarchar(200) NULL,
	[Field11] [datetime] NULL,
	[Field12] [datetime] NULL,
	[Field13] [datetime] NULL,
	[Field14] [datetime] NULL,
	[Field15] [datetime] NULL,
	[Field16] bit NULL,
	[Field17] bit NULL,
	[Field18] [float] NULL,
	[Executors] nvarchar(max) NULL,
	[UrgencyId] int NULL,
	[Field19] [float] NULL,
	[Field20] [float] NULL,
	[Topic] nvarchar(max) NULL,
	[Note] nvarchar(max) NULL,
 CONSTRAINT [PK_DOCS_DOCID] PRIMARY KEY ([DocumentId])
 )
