CREATE TABLE [dbo].[DOCS_APPLICATION](
	[AppId] int identity NOT NULL,
	[AppDocId] int NOT NULL,
	[AppApplierTypeId] int NULL,
	[AppName] nvarchar(100) NULL,
	[AppFirstname] nvarchar(100) NULL,
	[AppSurname] nvarchar(100) NULL,
	[AppLastName] nvarchar(100) NULL,
	[AppVoin] varchar(10) NULL,
	[AppYuridicalFormId] int NULL,
	[AppBirthdate] [date] NULL,
	[AppBirthCountryId] int NULL,
	[AppBirthRegionId] int NULL,
	[AppBirthDistrictId] int NULL,
	[AppSexId] int NULL,
	[AppFamilyStatusId] int NULL,
	[AppIsCitizen] [tinyint] NULL,
	[AppNationId] int NULL,
	[AppSosialStatusId] int NULL,
	[AppEducationLevelId] int NULL,
	[AppWorkingPlace] nvarchar(200) NULL,
	[AppPosition] nvarchar(200) NULL,
	[AppDocumentId] nvarchar(50) NULL,
	[AppDocumentTypeId] int NULL,
	[AppDocumentSerie] nvarchar(10) NULL,
	[AppDocumentNumber] nvarchar(20) NULL,
	[AppDocumentCountryId] int NULL,
	[AppDocumentBy] nvarchar(200) NULL,
	[AppDocumentDate] [date] NULL,
	[AppDocumentValidity] [date] NULL,
	[AppPhoneTypeId] int NULL,
	[AppPhonenumber] nvarchar(100) NULL,
	[AppEmail] nvarchar(100) NULL,
	[AppZip1] nvarchar(10) NULL,
	[AppCountry1Id] int NULL,
	[AppRegion1Id] int NULL,
	[AppDistrict1Id] int NULL,
	[AppAddress1] nvarchar(100) NULL,
	[AppZip2] nvarchar(10) NULL,
	[AppCountry2Id] int NULL,
	[AppRegion2Id] int NULL,
	[AppDistrict2Id] int NULL,
	[AppAddress2] nvarchar(100) NULL,
	[AppZip3] nvarchar(10) NULL,
	[AppCountry3Id] int NULL,
	[AppRegion3Id] int NULL,
	[AppDistrict3Id] int NULL,
	[AppAddress3] nvarchar(100) NULL,
	[AppCitizenshipId] int NULL,
	[AppRepresenterId] int NULL,
	[AppRepresenterDocument] nvarchar(200) NULL,
	[AppCezacekmeOrganizationId] int NULL,
	[AppAnonymId] [tinyint] NULL,
	[AppPhone1] nvarchar(100) NULL,
	[AppPhone2] nvarchar(100) NULL,
	[AppPhone3] nvarchar(100) NULL,
	[AppPhone4] nvarchar(100) NULL,
	[AppEmail1] nvarchar(100) NULL,
	[AppEmail2] nvarchar(100) NULL,
 CONSTRAINT [PK_DOCS_APPLICATION] PRIMARY KEY ([AppId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_COUNTRY] FOREIGN KEY([AppBirthCountryId]) REFERENCES [dbo].[DC_COUNTRY] ([CountryId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_DOCUMENTTYPE] FOREIGN KEY([AppDocumentTypeId]) REFERENCES [dbo].[DC_DOCUMENTTYPE] ([TypeId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_EDUCATIONLEVEL] FOREIGN KEY([AppEducationLevelId]) REFERENCES [dbo].[DC_EDUCATIONLEVEL] ([LevelId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_FAMILYSTATUS] FOREIGN KEY([AppFamilyStatusId]) REFERENCES [dbo].[DC_FAMILYSTATUS] ([FamilyId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_NATION] FOREIGN KEY([AppNationId]) REFERENCES [dbo].[DC_NATION] ([NationId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_PHONETYPE] FOREIGN KEY([AppPhoneTypeId]) REFERENCES [dbo].[DC_PHONETYPE] ([TypeId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_REGION_REGION1] FOREIGN KEY([AppRegion1Id]) REFERENCES [dbo].[DC_REGION] ([RegionId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_REGION_REGION2] FOREIGN KEY([AppRegion2Id]) REFERENCES [dbo].[DC_REGION] ([RegionId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_REGION_region3] FOREIGN KEY([AppRegion3Id]) REFERENCES [dbo].[DC_REGION] ([RegionId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_REPRESENTER] FOREIGN KEY([AppRepresenterId]) REFERENCES [dbo].[DC_REPRESENTER] ([RepresenterId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_SEX] FOREIGN KEY([AppSexId]) REFERENCES [dbo].[DC_SEX] ([SexId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_SOCIALSTATUS] FOREIGN KEY([AppSosialStatusId]) REFERENCES [dbo].[DC_SOCIALSTATUS] ([SocialId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DC_YURIDICALFORM] FOREIGN KEY([AppYuridicalFormId]) REFERENCES [dbo].[DC_YURIDICALFORM] ([FormId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DOC_APPLIERTYPE] FOREIGN KEY([AppApplierTypeId]) REFERENCES [dbo].[DOC_APPLIERTYPE] ([AppliertypeId]),
 CONSTRAINT [FK_DOCS_APPLICATION_DOCS] FOREIGN KEY([AppDocId]) REFERENCES [dbo].[DOCS] ([DocId])
)
