CREATE TABLE [dbo].[DOCS_READSTATUS](
	[DocId] int NOT NULL,
	[WorkplaceId] int NOT NULL,
	CONSTRAINT [FK_DOCS_READSTATUS_DC_WORKPLACE] FOREIGN KEY([WorkplaceId]) REFERENCES [dbo].[DC_WORKPLACE] ([WorkplaceId]),
	CONSTRAINT [FK_DOCS_READSTATUS_DOCS] FOREIGN KEY([DocId]) REFERENCES [dbo].[DOCS] ([DocId])
)
