CREATE TABLE [dbo].[DOCS](
	[DocId] int identity NOT NULL,
	[DocPeriodId] int NULL,
	[DocOrganizationId] int NOT NULL,
	[DocDoctypeId] int NOT NULL,
	[DocEnterdate] [date] NULL,
	[DocEnterno] nvarchar(50) NULL,
	[DocEnternop1] nvarchar(50) NULL,
	[DocEnternop2] int NULL,
	[DocEnternop3] int NULL CONSTRAINT [DF_DOCS_DocEnternop3]  DEFAULT 0,
	[DocEnternop4] int NULL,
	[DocRegisterId] int NULL,
	[DocEnternoControl] nvarchar(50) NULL,
	[DocDocno] nvarchar(50) NULL,
	[DocDocdate] [date] NULL,
	[DocDuplicateDocId] int NULL,
	[DocDuplicateId] int NULL,
	[DocFormId] int NULL,
	[DocReceivedFormId] int NULL,
	[DocBarcode] nvarchar(25) NULL,
	[DocPageCount] int NULL,
	[DocCopiesCount] int NULL,
	[DocAttachmentCount] int NULL,
	[DocAppliertypeId] int NULL,
	[DocUndercontrolStatusId] [tinyint] NOT NULL CONSTRAINT [DF__DOCS__DocUnderco__162F4418]  DEFAULT 0,
	[DocUndercontrolDayCount] int NULL,
	[DocControlStatusId] [tinyint] NOT NULL CONSTRAINT [DF__DOCS__DocControl__17236851]  DEFAULT 0,
	[DocControlDayCount] int NULL,
	[DocDocumentstatusId] int NULL CONSTRAINT [DF_DOCS_DocDocumentstatusId]  DEFAULT ((15)),
	[DocDescriptionId] int NULL,
	[DocDescription] nvarchar(max) NULL,
	[DocDescriptionR] nvarchar(max) NULL,
	[DocMainExecutorId] int NULL,
	[DocTopDepartmentId] int NULL,
	[DocPlannedDate] [date] NULL,
	[DocPlannedDateI] [date] NULL,
	[DocPlannedDateD] [date] NULL,
	[DocReportedDate] [date] NULL,
	[DocReportNote] nvarchar(500) NULL,
	[DocExecutedDate] [date] NULL,
	[DocProlongDate] [date] NULL,
	[DocSendDate] [datetime] NULL,
	[DocControlNotes] nvarchar(2000) NULL,
	[DocApplytypeId] int NULL,
	[DocTopicId] int NULL,
	[DocExecutionStatusId] int NULL,
	[DocSendedDocumentId] int NULL,
	[DocRelatedNIdn] int NULL,
	[DocRelatedtoSendedDocumentId] int NULL,
	[DocSendTypeId] int NULL,
	[DocTemplateId] int NULL,
	[DocClosed] [tinyint] NULL CONSTRAINT [DF__DOCS__DocClosed__18178C8A]  DEFAULT 0,
	[DocDeleted] [tinyint] NULL CONSTRAINT [DF__DOCS__DocDeleted__190BB0C3]  DEFAULT 0,
	[DocDeletedById] int NULL,
	[DocDeletedByDate] [datetime] NULL,
	[DocInsertedById] int NULL,
	[DocInsertedByDate] [datetime] NULL,
	[DocUpdatedById] int NULL,
	[DocUpdatedByDate] [datetime] NULL,
	[DocTopicType] int NULL,
	[DocIsAppealBoard] bit NOT NULL CONSTRAINT [DF__DOCS__DocIsAppealBoard]  DEFAULT 0,
	[DocReportedWorkplaceId] int NULL,
	[DocDocumentOldStatusId] int NULL,
	[DocResultId] int NULL,
	[DocNormTypeId] int NULL,
	[DocSendById] int NULL,
	[DocPrintedById] int NULL,
	[DocPrintedDate] [datetime] NULL,
    CONSTRAINT [PK_DOCS] PRIMARY KEY ([DocId]),
    CONSTRAINT [FK_DOCS_DC_DEPARTMENT] FOREIGN KEY([DocTopDepartmentId]) REFERENCES [dbo].[DC_DEPARTMENT] ([DepartmentId]),
    CONSTRAINT [FK_DOCS_DC_WORKPLACE] FOREIGN KEY([DocInsertedById]) REFERENCES [dbo].[DC_WORKPLACE] ([WorkplaceId]),
    CONSTRAINT [FK_DOCS_DC_WORKPLACE1] FOREIGN KEY([DocUpdatedById]) REFERENCES [dbo].[DC_WORKPLACE] ([WorkplaceId]),
	CONSTRAINT [FK_DOCS_DOC_APPLIERTYPE] FOREIGN KEY([DocAppliertypeId]) REFERENCES [dbo].[DOC_APPLIERTYPE] ([AppliertypeId]),
	CONSTRAINT [FK_DOCS_DOC_APPLYTYPE] FOREIGN KEY([DocApplytypeId]) REFERENCES [dbo].[DOC_APPLYTYPE] ([ApplytypeId]),
	CONSTRAINT [FK_DOCS_DOC_DESCRIPTION] FOREIGN KEY([DocDescriptionId]) REFERENCES [dbo].[DOC_DESCRIPTION] ([DescriptionId]),
	CONSTRAINT [FK_DOCS_DOC_DOCUMENTSTATUS] FOREIGN KEY([DocDocumentstatusId]) REFERENCES [dbo].[DOC_DOCUMENTSTATUS] ([DocumentstatusId]),
	CONSTRAINT [FK_DOCS_DOC_EXECUTIONSTATUS] FOREIGN KEY([DocExecutionStatusId]) REFERENCES [dbo].[DOC_EXECUTIONSTATUS] ([ExecutionstatusId]),
	CONSTRAINT [FK_DOCS_DOC_FORM] FOREIGN KEY([DocFormId]) REFERENCES [dbo].[DOC_FORM] ([FormId]),
	CONSTRAINT [FK_DOCS_DOC_PERIOD] FOREIGN KEY([DocPeriodId]) REFERENCES [dbo].[DOC_PERIOD] ([PeriodId]),
	CONSTRAINT [FK_DOCS_DOC_RECEIVED_FORM] FOREIGN KEY([DocReceivedFormId]) REFERENCES [dbo].[DOC_RECEIVED_FORM] ([ReceivedFormId]),
	CONSTRAINT [FK_DOCS_DOC_RESULT] FOREIGN KEY([DocResultId]) REFERENCES [dbo].[DOC_RESULT] ([Id]),
	CONSTRAINT [FK_DOCS_DOC_TOPIC] FOREIGN KEY([DocTopicId]) REFERENCES [dbo].[DOC_TOPIC] ([TopicId]),
	CONSTRAINT [FK_DOCS_DOC_TYPE] FOREIGN KEY([DocDoctypeId]) REFERENCES [dbo].[DOC_TYPE] ([DocTypeId])
)
