CREATE TABLE [dbo].[DOCS_EXECUTOR](
	[ExecutorId] int identity NOT NULL,
	[ExecutorDirectionId] int NOT NULL,
	[ExecutorDocId] int NOT NULL,
	[ExecutorWorkplaceId] int NOT NULL,
	[ExecutorFullName] nvarchar(500) NULL,
	[ExecutorMain] [tinyint] NOT NULL CONSTRAINT [DF__DOCS_EXEC__Execu__3F3159AB]  DEFAULT 0,
	[DirectionTypeId] int NULL,
	[ExecutorOrganizationId] int NULL,
	[ExecutorTopDepartment] int NULL,
	[ExecutorDepartment] int NULL,
	[ExecutorSection] int NULL,
	[ExecutorSubsection] int NULL,
	[ExecutorStepId] int NULL,
	[ExecutionstatusId] int NULL,
	[ExecutorNote] nvarchar(4000) NULL,
	[ExecutorReadStatus] bit NULL CONSTRAINT [DF_DOCS_EXECUTOR_ExecutorReadStatus]  DEFAULT 0,
	[ExecutorResolutionNote] nvarchar(4000) NULL,
	[SendStatusId] int NULL,
	[ExecutorPersonId] int NULL,
	[ExecutorStatus] bit NOT NULL CONSTRAINT [DF_dbo_DOCS_EXECUTOR_1]  DEFAULT 0,
	[ExecutorConfirmed] int NULL,
	[ExecutorNotDeleted] int NULL,
	[ExecutorControlStatus] bit NULL CONSTRAINT [DfDOCS_EXECUTORExecutorControlStatus] DEFAULT 0,
	[ExecutorTopId] int NULL,
    CONSTRAINT [PK_DOCS_EXECUTOR] PRIMARY KEY ([ExecutorId]),
    CONSTRAINT [FK_DOCS_EXECUTOR_DC_DEPARTMENT] FOREIGN KEY([ExecutorDepartment]) REFERENCES [dbo].[DC_DEPARTMENT] ([DepartmentId]),
	CONSTRAINT [FK_DOCS_EXECUTOR_DC_DEPARTMENT1] FOREIGN KEY([ExecutorTopDepartment]) REFERENCES [dbo].[DC_DEPARTMENT] ([DepartmentId]),
	CONSTRAINT [FK_DOCS_EXECUTOR_DC_WORKPLACE] FOREIGN KEY([ExecutorWorkplaceId]) REFERENCES [dbo].[DC_WORKPLACE] ([WorkplaceId]),
	CONSTRAINT [FK_DOCS_EXECUTOR_DOC_DIRECTIONTYPE] FOREIGN KEY([DirectionTypeId]) REFERENCES [dbo].[DOC_DIRECTIONTYPE] ([DirectionTypeId]),
	CONSTRAINT [FK_DOCS_EXECUTOR_DOC_EXECUTIONSTATUS] FOREIGN KEY([ExecutionstatusId]) REFERENCES [dbo].[DOC_EXECUTIONSTATUS] ([ExecutionstatusId]),
	CONSTRAINT [FK_DOCS_EXECUTOR_DOCS] FOREIGN KEY([ExecutorDocId]) REFERENCES [dbo].[DOCS] ([DocId]),
	CONSTRAINT [FK_DOCS_EXECUTOR_DOCS_DIRECTIONS] FOREIGN KEY([ExecutorDirectionId]) REFERENCES [dbo].[DOCS_DIRECTIONS] ([DirectionId])
)
