CREATE TABLE [dbo].[tempdocs_executor](
	[ExecutorId] int identity NOT NULL,
	[ExecutorDirectionId] int NOT NULL,
	[ExecutorDocId] int NOT NULL,
	[ExecutorWorkplaceId] int NOT NULL,
	[ExecutorFullName] nvarchar(500) NULL,
	[ExecutorMain] [tinyint] NOT NULL,
	[DirectionTypeId] int NULL,
	[ExecutorOrganizationId] int NULL,
	[ExecutorTopDepartment] int NULL,
	[ExecutorDepartment] int NULL,
	[ExecutorSection] int NULL,
	[ExecutorSubsection] int NULL,
	[ExecutorStepId] int NULL,
	[ExecutionstatusId] int NULL,
	[ExecutorNote] nvarchar(4000) NULL,
	[ExecutorReadStatus] bit NULL,
	[ExecutorResolutionNote] nvarchar(4000) NULL,
	[SendStatusId] int NULL,
	[ExecutorPersonId] int NULL,
	[ExecutorStatus] bit NOT NULL,
	[ExecutorConfirmed] int NULL,
	[ExecutorNotDeleted] int NULL,
	[ExecutorControlStatus] bit NULL,
	[ExecutorTopId] int NULL
)